### ISSUE TITLE
將 virtualenv 換成 pipenv

### ISSUE THREAD

**Issue by danny50610** [Inndy/twnhi-smartcard-agent#1]
pipenv 比 virtualenv 更方便 (個人使用兩三次的心得)

建議換成 pipenv ?

**Comment by nurockplayer** [comment]
其實可以直接改一改發個 PR 給作者

**Comment by Inndy** [comment]
我用 pipenv 的經驗沒有一次是好的，大多時候都不 work，不過還是歡迎發 PR，可以作為其中一種 dependency 安裝方式

**Comment by danny50610** [comment]
不過 pipenv 是使用 `Pipfile` 和 `Pipfile.lock` ，就不是 `requirements.txt` 了  
兩種檔案都留的話，怕未來會忘記更新另一種

其實也是看作者習慣用哪一套就好啦
只是個人私心推薦，畢竟我反而是 virtualenv 使用經驗比較不好
會用 pipenv ，主因是可以鎖定套件版本(包含其他相依)

如果近期不打算換 pipenv 的話，就先 close issue 吧
